ITEM.name = "Хлеб"
ITEM.base = "base_edible"
ITEM.model = Model("models/spec45as/stalker/items/bread.mdl")
ITEM.description = "Черствый батон, завезенный в Зону контрабандой или перекупленный у военных"
ITEM.category = "Food"
ITEM.width = 1 -- Width and height refer to how many grid spaces this item takes up.
ITEM.height = 1
ITEM.isDrink = false
ITEM.hungerGain = 20