ITEM.name = "Колбаса"
ITEM.base = "base_edible"
ITEM.model = Model("models/spec45as/stalker/items/kolbasa.mdl")
ITEM.description = "Хорошая качественная колбаса, произведенная в СССР"
ITEM.category = "Food"
ITEM.width = 1 -- Width and height refer to how many grid spaces this item takes up.
ITEM.height = 1
ITEM.isDrink = false
ITEM.hungerGain = 30